---
title: "A view of neuroscience from the perspective of building artificial systems"
description: ""
date: 2026-03-10
categories: [neuroscience]
---

Something that I have been thinking about recently is the question of how relavent the human connectome
is for creating artificial systems. The brain is divided into several parts: the cerebral cortex,
basal ganglia, hippocampus, amygdala, and so on, each with their own respective functions. At the outset,
this seems daunting - especially for people building intelligent systems that believe intelligence should
come from systems that look like the brain. However, there is this view that the specific wiring and compartmentalization is less important than one might think and that the learning rule is really what matters.

An interesting case study are the studies associated with British neuroscientist John Lorber. Lorber was studying hydrocephalus patients, people whose skulls had filled largely with cerebrospinal fluid, massively compressing brain tissue. In one case, he found that 90% of his patient's brain was empty, the remaining 10 percent coming from a thin rind of tissue outlining the inside of the skull. What's even crazier, the guy had a degree in mathematics, a completely normal social life, and had an IQ of 126! Lorber's framing was titled "Is your brain really necessary?", which sparked alot of controversy.

Pausing to think about this case study, one can rule out the need for specific compartments to be required for humans to be intelligent. I mean if they were, then these sorts of cases wouldn't exist. The condition for these cases to exist is that the brain was compressed gradually and slowly - over the course of years. Parts that were once essential for functionality had a chance to adapt to the new topology, and what remained is an incredibly dense network of neurons at the rim.

Judging from this, we can conclude that the learning rule seems to be what's more important. That is to say - the brain adapts, and a new view of the compartments of the brain can emerge. The fact that there is a "cerrebellum" here and a "hippocampus" there is mostly just a consequence of evolution adapting according to conditions and letting randomness stay if it works. In this case, stressing about why the brain has all the individual parts that it does is like stressing about why we exist with five fingers instead of six. Could it be that five-fingered humans had an evolutionary advantage over six-fingered humans and that all the six-fingered people were pruned out of the evolutionary tree? Maybe. A more plausible theory is that evolution found five fingers, it worked, and the design was never iterated upon. The brain, with all its glorious sections and compartments, can be viewed in the same way.

If one does take this view, it is great news for neuromorphic engineers, as it is a massive simplification of what makes systems actually intelligent and reduces the problems that a neuromorphic engineer would need to focus on. In the future, it could be that humans can specify the connectivity prior instead of evolution. With the view that it it probably won't matter too much, we can pick one thats more contrived and simpler (similar to deep learning networks on digital computers) and trust that it can produce intelligent behavior.