---
title: "Crossroads"
description: ""
date: 2026-01-18
categories: [blog]
---

Over the past few days, I've been talking to some friends about this sort of mini crisis that I'm having. In being interested in active matter, I thought that understanding theoretical condensed matter would probably be a good thing to do. You don't need every aspect of theoretical condensed matter physics to do work in active matter - it's probably overkill. In fact, I think the expertise of a chemist is probably more suited for work in condensed matter than a theoretical physicist. But this has encouraged my pursuit in learning theoretical physics anyways - for the reasons that 1. I'm interested in theoretical physics and 2. I know that it will be useful in my pursuit of AI down the line. However, there is another problem that has caught my attention, which is quantum gravity. Quantum gravity is interesting as a problem, first because it's literally a theory of everything. If one were able to produce such a theory that unifies the Standard Model as well as gravity, you'd essentially have a theory of everything - one model that when given the parameters would tell you how the universe evolves. Being ambitious, this obvious sounds like something interesting to work on. So part of my recent struggles has been attempting to reconcile these two interests: my pursuit of artificial intelligence and this problem of quantum gravity. After much toil and thinking, I'm thinking that it probably can't be done. At least, with my current viewpoints on how AI progress should be made as well as the nature of QG. They're just too different. Let me elaborate on how I view both of these.

My current perspective on artificial intelligence is that everyone is too LLM-pilled. Alot of time and effort has gone to studying these systems which granted, given their very impressive results since they were first released in 2017 as well as their subsequent scaling by OpenAI and various other companies has led to systems that can perform well on quite alot of tasks. To name some, I'll include essay writing, image generation/art (not exactly LLM based but can be combined with LLM querying), generally complex reasoning (solving complex maths, physics, and other science problems). I think I should even improve on my own understanding of LLMs - even though I can code them there's still alot of theory to be learned. Although with these tremendous advantages artificial systems still have a whole slew of tasks that they suck at compared to humans. These include sensorimotor tasks (how would one even solve sensotimor tasks with LLMS?), commonsense reasoning, and general creativity and pattern recognition. These observations can be summarized by Moravec's Paradox. It almost seems like there's a sort of "mutual orthogonality" of computational tasks that are solved by two parallel systems - one that's the digital computer, and the other the human brain. 

Moravec's Paradox has been a subject of both fascination and an integral part of my own research recently. The hypothesis is that the cause for it is due to the two different hardware systems that computational tasks are performed on. In other words, hardware is the issue. The paradox has been observed in every computational task that has been optimized on digital computers, and this fact has not changed since their inception in the 50s. Without going into too much detail, I forsee a revolution where the hardware is completely overturned, both in terms of the computational model that they implement as well as the materials that constitute them, possibly expanding to areas where the dominant computers are not made with silicon but something more exotic or unconventional by today's standards (photonics is an interesting direction). Hence my interest in condensed matter - being well educated in how materials work is part of my desire to bring about this revolution.

My motivation in high energy theoretical physics is completely independent from AI. As interesting as the problem of QG is, I don't think it can be reconciled with pursing artificial intelligence. Understanding quantum gravity first of all, requires an understanding of exotic mathematical structures, an understanding of the Standard Model and quantum field theory which would take me more years to develop, as well as an understanding of the current approaches such as string theory and lqg and their possible flaws. While I could very well forsee myself learning all of these things, it would certainly take out of my AI ambitions. They're just along two different axes - one is in the land of theory and mathematics, the other in the axis of engineering and computer science. It is a sad but unofortunate reality - that I'd be spreading myself too thin if I tried to do both. For now, the two paths are along the same axes - quantum field theory (as established by my discussion before), but at some point I will have to step back to the AI path. Maybe during retirement I can return to this - if it hasn't been solved already. Maybe.